### PR TITLE
Feat: add mobile guide

### PR DESCRIPTION
**Pull request by omxpro**

### CODE REVIEW

**Comment by omxpro** [comment]
@LukaHietala you may have forgot to review this.

**Comment by JasonLovesDoggo** [comment]
No....

**Comment by omxpro** [comment]
> No....

???

**Comment by JasonLovesDoggo** [comment]
> > No....
> 
> ???

.........

**Comment by LukaHietala** [comment]
I see that you have put a lot of effort into that, but the Reddit bot has some problems with phones and we don't natively support it. This will not be merged. 😢

**Comment by omxpro** [comment]
> I see that you have put a lot of effort into that, but the Reddit bot has some problems with phones and we don't natively support it. This will not be merged. 😢

I just resseted my phone and if you follow my instructions it works correctly. I also run it on ghub actions

**Pull request closed without merging**
