### PR TITLE
Major Rework

### PR DESCRIPTION
**Pull request by micziz**
## Major Rework of the Documentation

- Small changes to readme.md
- Complete refactor of reddit API details. Rename to configuration, update to config.toml
- Delete errors folder and put everything in a troubleshooting.md
- Add descriptions to all files
- Fix all the markdownlint violations
- Major rework of playwright.md

## Question

Where can i find documentation?

### CODE REVIEW

**Comment by LukaHietala** [comment]
You can find the documentation here. [Reddit Bot Docs](https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/). And if this PR is still in progress you can convert it to a draft. 😄

**Comment by micziz** [comment]
The Pull Request Is ready!

**Comment by LukaHietala** [comment]
Why did you remove the error pages at `Rework 2`?

**Comment by LukaHietala** [comment]
Thanks a lot!

**Comment by micziz** [comment]
NP

**Pull request merged**
